stages:
    - tests

test:
    image: python:3.11
    stage: tests
    before_script:
        - pip install uv
        - uv pip compile pyproject.toml -o requirements.txt
        - pip install -r requirements.txt
        - pip install unittest-xml-reporting 
    script:
        - python -m xmlrunner discover -s src/python -o test-reports
    artifacts:
        paths:
            - test-reports/
        reports:
            junit: test-reports/*.xml

