services:
  web:
    build: 
      context: .
      dockerfile: src/flask_app/Dockerfile
    container_name: dartscoremate_flask
    ports:
      - "5000:5000"
    command: gunicorn --bind 0.0.0.0:5000 src.flask_app.main:app
  streamlit:
    build:
      context: .
      dockerfile: src/pic_snap/Dockerfile
    container_name: picsnap_streamlit
    ports:
      - "8501:8501"
    command: streamlit run src/pic_snap/app.py

  