services:
  web:
    build: 
      context: .
      dockerfile: src/flask_app/Dockerfile
    container_name: dartscoremate_flask
    ports:
      - "5000:5000"
    command: gunicorn --bind 0.0.0.0:5000 src.flask_app.main:app
    # give docker container access to usb cameras, commented out because build will fail if devices are not found
    #devices:
    #  - "/dev/video0:/dev/video0"
    #  - "/dev/video1:/dev/video1"
    #  - "/dev/video2:/dev/video2"
    #  - "/dev/video3:/dev/video3"
    #  - "/dev/video4:/dev/video4"
    #  - "/dev/video5:/dev/video5"
    #  - "/dev/video6:/dev/video6"
    #  - "/dev/video7:/dev/video7"

  # --> alternative: priveledged mode
    privileged: true  # Grant the container additional privileges (including device access)
  streamlit:
    build:
      context: .
      dockerfile: src/pic_snap/Dockerfile
    container_name: picsnap_streamlit
    ports:
      - "8501:8501"
    # give docker container access to usb cameras
    #devices:
    #  - "/dev/video0:/dev/video0"
    #  - "/dev/video1:/dev/video1"
    #  - "/dev/video2:/dev/video2"
    #  - "/dev/video3:/dev/video3"
    #  - "/dev/video4:/dev/video4"
    #  - "/dev/video5:/dev/video5"
    #  - "/dev/video6:/dev/video6"
    #  - "/dev/video7:/dev/video7"
    privileged: true
    command: streamlit run src/pic_snap/app.py

  